### PR TITLE
Link to external documentation with reference in mkdocs.yaml

### PR DESCRIPTION
**Pull request by gregorylegarec**
(Something went terribly wrong with #72, I don't really understand why, maybe a confusion between `master` and `dev`)

This PR started with the idea of adding the [apps registry documentation](https://github.com/cozy/cozy-apps-registry) into Cozy main documentation. But the cozy-apps-registry is not really an API reference like cozy-client-js or cozy-konnectors-libs.

So I tried to aim something like this in `mkdocs.yaml`, `cozy-apps-registry` being just here a reference to the repository from the file `OUTSIDE_DOCS`:
```yaml
- Create your first app: dev/app.md
- Develop a connector: dev/konnector.md
- App registry: cozy-apps-registry
- Create a mobile app with cordova: dev/cordova.md
```
I eventually succeed in tears and blood as I am not really familiar with Python.

During my work, I felt that it was interesting to improve the documentation scripts in the following ways:
* Check if gettext is installed and warn the user about it
* Check if entries list are empty in `add_external_docs.py`. It can happen when `fetch.sh` has not been called and no external documentation is present.
* Rename `OUTSIDE_DOCS` to `EXTERNAL_DOCS` which feel more consistent to me, but I may be wrong on this point.
* build a `mkdocs.out.yaml` to work with and generate the documentation from. It avoids locally to rewrite always the same file and introduce side effects.

### CODE REVIEW

**Comment by nono** [comment]
@gregorylegarec FYI, there is a conflict on `add_external_docs.py`

**Comment by gregorylegarec** [comment]
@nono I know it, I need to update some part of the code also.

**Comment by ptbrowne** [comment]
Is this PR still relevant @gregorylegarec

**Comment by gregorylegarec** [comment]
@ptbrowne Sorry for forgetting this PR.

I think this may be still relevant but not enough to spend my time on it for now. Let's close it for now.

**Pull request closed without merging**
