### PR TITLE
Add client_max_body_size to nginx config.

### PR DESCRIPTION
**Pull request by nicofrand**

### CODE REVIEW

**Comment by clochix** [comment]
Ping @aeris Any idea why this is necessary?

**Comment by nicofrand** [comment]
Maybe this should be set to 0, not sure what are the risks: http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

**Comment by aeris** [comment]
Not necessary here, because it's the default vhost, not use but only for Let's Encrypt and http to https redirection.
For instance vhosts, [`client_max_body_size` is set to 1GB](https://github.com/cozy/cozy-coclyco/blob/master/cozy/coclyco/nginx.conf#L12)

**Comment by nicofrand** [comment]
Oops my bad, I re-read the documentation too quickly.

**Pull request closed without merging**
