### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by sblaisot**
- Do not exclude cozy-stack/docs/archives because they are referenced from other cozy-stack documentations
- Fix broken link to konnector tutorial

### CODE REVIEW

**Comment by Crash--** [comment]
We ended up excluding `cozy-stack/docs/archives` because... of https://github.com/cozy/cozy.github.io/issues/198 

But what I understand from your PR is that, excluding the folder doesn't only exclude it for the search index but also for associated links? If yes, it's an issue and in that case we can add the folder again but we should find something to exclude it from the search index. It's a bit weird to see "archived" documentation came first during a search...

**Comment by sblaisot** [comment]
The archives folder has not only been excluded from search, it has been excluded completely from documentation.

However, this is not realy archived documentation because there are active links from current documentation to archived ones.

So we have two solutions:
1. Consider it's active documentation as long as there are active links to it so thre is no reason to exclude that documentation from including and showing in search results
2. If it's archives documentation that should not be published anymore, remove active links to it (https://github.com/cozy/cozy-stack/blob/master/docs/README.md?plain=1#L54-L66)

**Comment by sblaisot** [comment]
We could add mkdocs exclude-search plugin https://github.com/chrieke/mkdocs-exclude-search

**Comment by sblaisot** [comment]
Ok, I updated this PR to exclude `cozy-stack/archives/*` from search results keeping them published

**Review by Crash-- — APPROVED** [review]
Nice way to solve the issue now! <3

**Review by nono — APPROVED** [review]

**Pull request merged**
