### PR TITLE
[WIP] doc: update cordova documentation

### PR DESCRIPTION
**Pull request by enguerran**

### CODE REVIEW

**Comment by nono** [comment]
@enguerran is it still a work in progress?

**Comment by enguerran** [comment]
[I don't know if I have to reference `cozy/cozy-client-js` or `cozy/cozy-client`](https://mattermost.cozycloud.cc/test-team/pl/h4nfro53nfb87gdc7rimhmidpa) for paragraphes regarding OAuth and data fetches.

And I did not take the time to complete this task.

So yes, it is still in progress, but I need some help here.

**Comment by nono** [comment]
> I don't know if I have to reference cozy/cozy-client-js or cozy/cozy-client for paragraphes regarding OAuth and data fetches.

Let's say [cozy-client](https://github.com/cozy/cozy-client)

**Comment by enguerran** [comment]
Okay, so I need to check how to use `cozy-client` within cordova. More to come.

**Comment by ptbrowne** [comment]
@enguerran How can we help ?

**Comment by enguerran** [comment]
@ptbrowne I don't know, it's been a while I worked on this. I don't do cordova anymore, I need to deep dive to the new standards for Cozy application development (including mobile) before I can update this documentation.

**Comment by CPatchane** [comment]
@enguerran Have you any updates on this PR?

**Comment by enguerran** [comment]
Cannot find an opportunity to continue.

**Pull request closed without merging**
